### ISSUE TITLE
Subnamespace `botcar`

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/cts-sns-registry#1]
Please supply the following information.

Subnamespace abbreviation:  botcar

URI for the subnamespace: http://folio2.furman.edu/ns/botcar

Summary description (one line) of the corpus identified by this subnamespace:  Texts related to the early scientific exploration of the Carolinas. Identified by the Botanica Caroliniana Project.

Name of contact person: Christopher W. Blackwell

Contact email: christopher.blackwell@furman.edu

URL for more information about identifiers in this subnamespace: http://folio.furman.edu/projects/botanicacaroliniana/index.html

**Comment by neelsmith** [comment]
The `botcar` namespace has been added to the CTS subnamespace registry and will be published as part of the `urn:cite2:cite:ctssns.v1:` collection.

**Comment by Eumaeus** [comment]
Please supply the following information.

Subnamespace abbreviation:  botcar

URI for the subnamespace: http://folio2.furman.edu/ns/botcar

Summary description (one line) of the corpus identified by this subnamespace:  Texts related to the early scientific exploration of the Carolinas. Identified by the Botanica Caroliniana Project.

Name of contact person: Christopher W. Blackwell

Contact email: christopher.blackwell@furman.edu

URL for more information about identifiers in this subnamespace: https://github.com/Eumaeus/fuCiteDX/blob/master/namespaces.md

**Comment by neelsmith** [comment]
The record for the CITE2 subnamespace botcar has been updated and will be published in version 1.0.1 of the registry.
