### ISSUE TITLE
Subnamespace `fufolio`

### ISSUE THREAD

**Issue by Eumaeus** [cite-architecture/cts-sns-registry#2]
Please supply the following information.

Subnamespace abbreviation:  fufolio

URI for the subnamespace: http://folio.furman.edu

Summary description (one line) of the corpus identified by this subnamespace:  Miscellaneous modern literary texts for teaching and research at Furman University.

Name of contact person: Christopher Blackwell

Contact email: christopher.blackwell@furman.edu

URL for more information about identifiers in this subnamespace: http://folio.furman.edu/cite.html

**Comment by neelsmith** [comment]
The fufolio namespace has been added to the CTS subnamespace registry and will be published as part of the urn:cite2:cite:ctssns.v1: collection.

**Comment by Eumaeus** [comment]
Please supply the following information.

Subnamespace abbreviation:  fufolio

URI for the subnamespace: http://folio.furman.edu

Summary description (one line) of the corpus identified by this subnamespace:  Miscellaneous modern literary texts for teaching and research at Furman University.

Name of contact person: Christopher Blackwell

Contact email: christopher.blackwell@furman.edu

URL for more information about identifiers in this subnamespace: https://github.com/Eumaeus/fuCiteDX/blob/master/namespaces.md

**Comment by neelsmith** [comment]
The record for cts subnamespace fufoio has been updated and will be published in version 1.0.1 of the CTS subnamespaces registry.
